### ISSUE TITLE
Running sbt coverage +test +coverageReport +coveralls throws error

### ISSUE THREAD

**Issue by MarkPhilipps** [scoverage/sbt-scoverage-samples#29]
Hey, I'm trying to get the sample project to work locally, as my own project throws the same error. At first I thought it was my project, but the example throws the following error for me when I run "sbt coverage +test +coverageReport +coveralls":

[error] java.util.NoSuchElementException: key not found: org/scoverage/samples/TypeTreeObjects.scala
[error]         at scala.collection.MapLike.default(MapLike.scala:236)
[error]         at scala.collection.MapLike.default$(MapLike.scala:235)
[error]         at scala.collection.AbstractMap.default(Map.scala:65)
[error]         at scala.collection.MapLike.apply(MapLike.scala:144)
[error]         at scala.collection.MapLike.apply$(MapLike.scala:143)
[error]         at scala.collection.AbstractMap.apply(Map.scala:65)
[error]         at org.scoverage.coveralls.CoberturaMultiSourceReader.lineCoverage(CoberturaMultiSourceReader.scala:119)
[error]         at org.scoverage.coveralls.CoberturaMultiSourceReader.reportForSource(CoberturaMultiSourceReader.scala:130)
[error]         at org.scoverage.coveralls.CoverallsPlugin$.$anonfun$coverallsTask$6(CoverallsPlugin.scala:125)
[error]         at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:116)
[error]         at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:113)
[error]         at scala.collection.parallel.immutable.ParHashSet$ParHashSetIterator.map2combiner(ParHashSet.scala:81)
[error]         at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1064)
[error]         at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error]         at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error]         at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error]         at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1061)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error]         at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:396)
[error]         at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:721)
[error]         at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:379)
[error]         at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:379)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
[error]         at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
[error]         at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:416)
[error]         at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:60)
[error]         at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult(Tasks.scala:555)
[error]         at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult$(Tasks.scala:555)
[error]         at scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:84)
[error]         at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:968)
[error]         at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error]         at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error]         at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error]         at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:963)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error]         at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[error] (coveralls) java.util.NoSuchElementException: key not found: org/scoverage/samples/TypeTreeObjects.scala
[error] Total time: 1 s, completed 16.01.2023, 18:30:11

**Comment by rolandtritsch** [comment]
Hi Mark. Just tried it ...

```
~/Development/Home/sbt-scoverage-samples (main ✔) ᐅ git pull
Already up-to-date.
~/Development/Home/sbt-scoverage-samples (main ✔) ᐅ git status
On branch main
Your branch is up-to-date with 'origin/main'.

nothing to commit, working tree clean
~/Development/Home/sbt-scoverage-samples (main ✔) ᐅ sbt +clean +coverage +test +coverageReport 
[info] welcome to sbt 1.7.1 (Oracle Corporation Java 18)
[info] loading settings for project sbt-scoverage-samples-build-build-build from metals.sbt ...
[info] loading project definition from /home/roland/Development/Home/sbt-scoverage-samples/project/project/project
[info] loading settings for project sbt-scoverage-samples-build-build from metals.sbt ...
[info] loading project definition from /home/roland/Development/Home/sbt-scoverage-samples/project/project
[success] Generated .bloop/sbt-scoverage-samples-build-build.json
[success] Total time: 0 s, completed 17 Jan 2023, 08:46:11
[info] loading settings for project sbt-scoverage-samples-build from metals.sbt,plugins.sbt ...
[info] loading project definition from /home/roland/Development/Home/sbt-scoverage-samples/project
[success] Generated .bloop/sbt-scoverage-samples-build.json
[success] Total time: 0 s, completed 17 Jan 2023, 08:46:11
[info] loading settings for project sbt-scoverage-samples from build.sbt ...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Setting Scala version to 2.13.9 on 1 projects.
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[success] Total time: 0 s, completed 17 Jan 2023, 08:46:12
[info] Setting Scala version to 3.2.2-RC2 on 1 projects.
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[success] Total time: 0 s, completed 17 Jan 2023, 08:46:12
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Forcing Scala version to 2.13.9 on all projects.
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Defining ThisBuild / coverageEnabled
[info] The new value will be used by Compile / compile / scalacOptions, libraryDependencies
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Forcing Scala version to 3.2.2-RC2 on all projects.
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Defining ThisBuild / coverageEnabled
[info] The new value will be used by Compile / compile / scalacOptions, libraryDependencies
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Setting Scala version to 2.13.9 on 1 projects.
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] compiling 17 Scala sources to /home/roland/Development/Home/sbt-scoverage-samples/target/scala-2.13/classes ...
[info] scoverage excludedSymbols: List(scala.reflect.api.Exprs.Expr, scala.reflect.api.Trees.Tree, scala.reflect.macros.Universe.Tree)
[info] Cleaning datadir [/home/roland/Development/Home/sbt-scoverage-samples/target/scala-2.13/scoverage-data]
[info] Beginning coverage instrumentation
[info] Instrumentation completed [246 statements]
[info] Wrote instrumentation file [/home/roland/Development/Home/sbt-scoverage-samples/target/scala-2.13/scoverage-data/scoverage.coverage]
[info] Will write measurement data to [/home/roland/Development/Home/sbt-scoverage-samples/target/scala-2.13/scoverage-data]
[info] compiling 10 Scala sources to /home/roland/Development/Home/sbt-scoverage-samples/target/scala-2.13/test-classes ...
Received a credit request
Received a credit request
[info] CreditEngineTest:
[info] a credit engine
[info] - should approve amounts under the minimum
[info] - should reject amounts over the min
[info] SimpleObject2Test:
[info] - invoking simpleobject2
[info] FuturesTest:
[info] - futures happy path
[info] PriceEngineTest:
[info] a price engine
[info] - should broadcast on startup
[info] - should stop broadcasting on StopService msg
[info] - should restart broadcasting on StartService message
[info] CharmaxTest:
[info] a char max
[info] - should not crash the XML writer
[info] OrderEngineTest:
[info] an order engine
[info] - should create an order if credit approved
[info] - should reject order if credit denied
[info] - should send a credit request if a quote is available
Sending order request
[info] ClientActorTest:
[info] a client actor
[info] - should ask for a quote
[info] - should send a market order request if ask under minimum
[info] - should not send an order request if ask is over minimum
[info] DefaultArgumentsObjectTest:
[info] DefaultArgumentsObject
[info] - should execute the default block if no arg is given
[info] OrderValidatorTest:
[info] an order validator
[info] - should throw exception
[info] SimpleClassTest:
[info] a SimpleClassTest
[info] - should test 1
[info] Run completed in 6 seconds, 233 milliseconds.
[info] Total number of tests run: 17
[info] Suites: completed 10, aborted 0
[info] Tests: succeeded 17, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 14 s, completed 17 Jan 2023, 08:46:29
[info] Setting Scala version to 3.2.2-RC2 on 1 projects.
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] compiling 17 Scala sources to /home/roland/Development/Home/sbt-scoverage-samples/target/scala-3.2.2-RC2/classes ...
[info] compiling 10 Scala sources to /home/roland/Development/Home/sbt-scoverage-samples/target/scala-3.2.2-RC2/test-classes ...
Received a credit request
Received a credit request
[info] CreditEngineTest:
[info] a credit engine
[info] - should approve amounts under the minimum
[info] - should reject amounts over the min
[info] SimpleObject2Test:
[info] - invoking simpleobject2
[info] FuturesTest:
[info] - futures happy path
[info] PriceEngineTest:
[info] a price engine
[info] - should broadcast on startup
[info] - should stop broadcasting on StopService msg
[info] - should restart broadcasting on StartService message
[info] CharmaxTest:
[info] a char max
[info] - should not crash the XML writer
[info] OrderEngineTest:
[info] an order engine
[info] - should create an order if credit approved
[info] - should reject order if credit denied
[info] - should send a credit request if a quote is available
Sending order request
[info] ClientActorTest:
[info] a client actor
[info] - should ask for a quote
[info] - should send a market order request if ask under minimum
[info] - should not send an order request if ask is over minimum
[info] DefaultArgumentsObjectTest:
[info] DefaultArgumentsObject
[info] - should execute the default block if no arg is given
[info] OrderValidatorTest:
[info] an order validator
[info] - should throw exception
[info] SimpleClassTest:
[info] a SimpleClassTest
[info] - should test 1
[info] Run completed in 6 seconds, 256 milliseconds.
[info] Total number of tests run: 17
[info] Suites: completed 10, aborted 0
[info] Tests: succeeded 17, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 14 s, completed 17 Jan 2023, 08:46:43
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Setting Scala version to 2.13.9 on 1 projects.
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Waiting for measurement data to sync...
[info] Reading scoverage instrumentation [/home/roland/Development/Home/sbt-scoverage-samples/target/scala-2.13/scoverage-data/scoverage.coverage]
[info] Reading scoverage measurements...
[info] Generating scoverage reports...
[info] Written Cobertura report [/home/roland/Development/Home/sbt-scoverage-samples/target/scala-2.13/coverage-report/cobertura.xml]
[info] Written XML coverage report [/home/roland/Development/Home/sbt-scoverage-samples/target/scala-2.13/scoverage-report/scoverage.xml]
[info] Written HTML coverage report [/home/roland/Development/Home/sbt-scoverage-samples/target/scala-2.13/scoverage-report/index.html]
[info] Statement coverage.: 71.54%
[info] Branch coverage....: 60.98%
[info] Coverage reports completed
[error] Coverage is below minimum [60.98% < 70.00%]: Branch:Total
[info] All done. Coverage was stmt=[71.54%] branch=[60.98%]
[success] Total time: 1 s, completed 17 Jan 2023, 08:46:45
[info] Setting Scala version to 3.2.2-RC2 on 1 projects.
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Waiting for measurement data to sync...
[info] Reading scoverage instrumentation [/home/roland/Development/Home/sbt-scoverage-samples/target/scala-3.2.2-RC2/scoverage-data/scoverage.coverage]
[info] Reading scoverage measurements...
[info] Generating scoverage reports...
[info] Written Cobertura report [/home/roland/Development/Home/sbt-scoverage-samples/target/scala-3.2.2-RC2/coverage-report/cobertura.xml]
[info] Written XML coverage report [/home/roland/Development/Home/sbt-scoverage-samples/target/scala-3.2.2-RC2/scoverage-report/scoverage.xml]
[info] Written HTML coverage report [/home/roland/Development/Home/sbt-scoverage-samples/target/scala-3.2.2-RC2/scoverage-report/index.html]
[info] Statement coverage.: 64.91%
[info] Branch coverage....: 33.33%
[info] Coverage reports completed
[error] Coverage is below minimum [33.33% < 70.00%]: Branch:Total
[info] All done. Coverage was stmt=[64.91%] branch=[33.33%]
[success] Total time: 1 s, completed 17 Jan 2023, 08:46:46
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
```

Works for me (tm) :) ...

**Comment by rolandtritsch** [comment]
I am on ...

```
java            openjdk-18      /home/roland/.tool-versions
sbt             1.8.0           /home/roland/.tool-versions
```

The sbt version should make no difference. The java version can make a difference.

**Comment by MarkPhilipps** [comment]
Hello, thank you for the quick reply. 
I tried it with sbt version 1.7.1 and 1.8.0. As you say - no difference. 
But I am actually on openjdk-17. I will try it later and report again. 
Thanks again.

**Comment by MarkPhilipps** [comment]
Hello again,
unfortunately I did not manage to test it yesterday, sorry for that.
So I changed the jdk:
`PS C:\Repos\sbt-scoverage-samples> java -version
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment (build 18.0.2.1+1-1)
OpenJDK 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)`

And also made sure that I have no changes:
`PS C:\Repos\sbt-scoverage-samples> git pull
Already up to date.
PS C:\Repos\sbt-scoverage-samples> git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean`

The problem is not that `sbt +clean +coverage +test +coverageReport ` is not working.
This also works for me.
But I am trying to upload it to coveralls.io with `sbt coverage +test +coverageReport +coveralls` as described in the readme.
This command gives me the following output:
`PS C:\Repos\sbt-scoverage-samples> sbt coveralls                                             
[info] welcome to sbt 1.7.1 (Oracle Corporation Java 18.0.2.1)
[info] loading settings for project sbt-scoverage-samples-build from plugins.sbt ...
[info] loading project definition from C:\Repos\sbt-scoverage-samples\project
[info] loading settings for project sbt-scoverage-samples from build.sbt ...
[info] set current project to sbt-scoverage-samples (in build file:/C:/Repos/sbt-scoverage-samples/)
[info] Repository = .\.git
[info] sbt-coveralls: Generating reports for 17 files ...
[error] java.util.NoSuchElementException: key not found: org/scoverage/samples/TypeTreeObjects.scala
[error]         at scala.collection.MapLike.default(MapLike.scala:236)
[error]         at scala.collection.MapLike.default$(MapLike.scala:235)
[error]         at scala.collection.AbstractMap.default(Map.scala:65)
[error]         at scala.collection.MapLike.apply(MapLike.scala:144)
[error]         at scala.collection.MapLike.apply$(MapLike.scala:143)
[error]         at scala.collection.AbstractMap.apply(Map.scala:65)
[error]         at org.scoverage.coveralls.CoberturaMultiSourceReader.lineCoverage(CoberturaMultiSourceReader.scala:119)
[error]         at org.scoverage.coveralls.CoberturaMultiSourceReader.reportForSource(CoberturaMultiSourceReader.scala:130)
[error]         at org.scoverage.coveralls.CoverallsPlugin$.$anonfun$coverallsTask$6(CoverallsPlugin.scala:125)
[error]         at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:116)
[error]         at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:113)
[error]         at scala.collection.parallel.immutable.ParHashSet$ParHashSetIterator.map2combiner(ParHashSet.scala:81)
[error]         at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1064)
[error]         at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error]         at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error]         at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error]         at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1061)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error]         at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[error]         at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
[error]         at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:670)
[error]         at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:379)
[error]         at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:379)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
[error]         at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
[error]         at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:416)
[error]         at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:60)
[error]         at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult(Tasks.scala:555)
[error]         at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult$(Tasks.scala:555)
[error]         at scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:84)
[error]         at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:968)
[error]         at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error]         at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
[error]         at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
[error]         at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:963)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error]         at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[error] (coveralls) java.util.NoSuchElementException: key not found: org/scoverage/samples/TypeTreeObjects.scala
[error] Total time: 1 s, completed 18.01.2023, 13:45:15`

I tried it with sbt 1.8.0 & 1.7.1 and openJDK 17,18 and 19.

**Comment by rolandtritsch** [comment]
```
~/Development/Home/sbt-scoverage-samples (main ✔) ᐅ sbt +coveralls
[info] welcome to sbt 1.7.1 (Oracle Corporation Java 18)
[info] loading settings for project sbt-scoverage-samples-build-build-build from metals.sbt ...
[info] loading project definition from /home/roland/Development/Home/sbt-scoverage-samples/project/project/project
[info] loading settings for project sbt-scoverage-samples-build-build from metals.sbt ...
[info] loading project definition from /home/roland/Development/Home/sbt-scoverage-samples/project/project
[success] Generated .bloop/sbt-scoverage-samples-build-build.json
[success] Total time: 0 s, completed 18 Jan 2023, 15:07:13
[info] loading settings for project sbt-scoverage-samples-build from metals.sbt,plugins.sbt ...
[info] loading project definition from /home/roland/Development/Home/sbt-scoverage-samples/project
[success] Generated .bloop/sbt-scoverage-samples-build.json
[success] Total time: 0 s, completed 18 Jan 2023, 15:07:14
[info] loading settings for project sbt-scoverage-samples from build.sbt ...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Setting Scala version to 2.13.9 on 1 projects.
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Repository = ./.git
[info] sbt-coveralls: Generating reports for 16 files ...
[info] sbt-coveralls: Adding file reports to the coveralls file (coveralls.json) ...
[info] sbt-coveralls: Uploading the coveralls file (coveralls.json) ...
[info] sbt-coveralls: Uploading to https://coveralls.io succeeded (results may not appear immediately): Job ##54.1/https://coveralls.io/jobs/113132838
[success] Total time: 6 s, completed 18 Jan 2023, 15:07:21
[info] Setting Scala version to 3.2.2-RC2 on 1 projects.
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
[info] Repository = ./.git
[info] sbt-coveralls: Generating reports for 17 files ...
[info] sbt-coveralls: Adding file reports to the coveralls file (coveralls.json) ...
[info] sbt-coveralls: Uploading the coveralls file (coveralls.json) ...
[info] sbt-coveralls: Uploading to https://coveralls.io succeeded (results may not appear immediately): Job ##55.1/https://coveralls.io/jobs/113132839
[success] Total time: 1 s, completed 18 Jan 2023, 15:07:22
[info] Reapplying settings...
[info] set current project to sbt-scoverage-samples (in build file:/home/roland/Development/Home/sbt-scoverage-samples/)
```

Hhhmmm ... bad news: Works for me.

But ... I am just seeing that you run on `Windows`. I am running on `Ubuntu`. Need to dive into this a little bit more. But it will be the weekend before I have time to look at this.

**Comment by rolandtritsch** [comment]
Hhhmmm ... nope. Windows is working. Will continue digging ...

![image](https://user-images.githubusercontent.com/671381/213868662-7b9fa49d-a54f-4ebc-b38d-cd5999348870.png)

**Comment by rolandtritsch** [comment]
Closing due to inactivity.
