### ISSUE TITLE
mvn build fails

### ISSUE THREAD

**Issue by davebo** [scoverage/sbt-scoverage-samples#5]
```
[INFO] 
[INFO] --- scala-maven-plugin:3.1.6:compile (compile) @ scoverage-samples ---
[INFO] /home/dbottger/git/scoverage/scoverage-samples/src/main/scala:-1: info: compiling
[INFO] Compiling 18 source files to /home/dbottger/git/scoverage/scoverage-samples/target/classes at 1412628812153
[INFO] compiler plugin: BasicArtifact(org.scoverage,scalac-scoverage-plugin_2.11,0.99.2,null)
[INFO] [scoverage]: Begin pre-instrumentation phase
[INFO] [scoverage]: Pre-instrumentation complete
[ERROR] ======= Position error
[INFO] Overlapping trees (63054,63049)
[INFO] == Ancestor tree [63070] of type Template at [92:240]TypeTreeObjects.scala
[INFO] 
[INFO] [L   4        ] #63070  [92:240]        Template   // {
[INFO] 
[INFO] == First overlapping tree [63054] of type Select at [208:236]TypeTreeObjects.scala
[INFO] 
[INFO] [L   8        ] #63054  [208:236]       Select     // new Container().typeParamAndD
[INFO] 
[INFO] == Second overlapping tree [63049] of type TypeTree at [232:235]TypeTreeObjects.scala
[INFO] 
[INFO] [L   8        ] #63049  [232:235]       TypeTree   // Any]
[INFO] 
[INFO] 
[INFO] While validating #63072
[INFO] [L   1        ] #63072  [0:240]         PackageDef // samples
[INFO] 
[INFO] Children:
[INFO]   [L   1 P#63072] #1681   [8:38]          Select     // samples
[INFO]   [L   4 P#63072] #63071  [70:240]        ClassDef   // TypeTreeObjects {
[INFO] =======
[ERROR] error: scala.reflect.internal.Positions$ValidateException: Overlapping trees (63054,63049)
[ERROR]     at scala.reflect.internal.Positions$class.positionError$1(Positions.scala:105)
[ERROR]     at scala.reflect.internal.Positions$class.validate$1(Positions.scala:135)
[ERROR]     at scala.reflect.internal.Positions$class.validate$1(Positions.scala:145)
[ERROR]     at scala.reflect.internal.Positions$class.validate$1(Positions.scala:145)
[ERROR]     at scala.reflect.internal.Positions$class.validatePositions(Positions.scala:150)
[ERROR]     at scala.reflect.internal.SymbolTable.validatePositions(SymbolTable.scala:16)
[ERROR]     at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:103)
[ERROR]     at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:430)
[ERROR]     at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
[ERROR]     at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
[ERROR]     at scala.collection.Iterator$class.foreach(Iterator.scala:743)
[ERROR]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
[ERROR]     at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
[ERROR]     at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1625)
[ERROR]     at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1610)
[ERROR]     at scala.tools.nsc.Global$Run.compileSources(Global.scala:1605)
[ERROR]     at scala.tools.nsc.Global$Run.compile(Global.scala:1703)
[ERROR]     at scala.tools.nsc.Driver.doCompile(Driver.scala:34)
[ERROR]     at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[ERROR]     at scala.tools.nsc.Driver.process(Driver.scala:55)
[ERROR]     at scala.tools.nsc.Driver.main(Driver.scala:68)
[ERROR]     at scala.tools.nsc.Main.main(Main.scala)
[ERROR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ERROR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]     at java.lang.reflect.Method.invoke(Method.java:606)
[ERROR]     at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR]     at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[ERROR] java.lang.reflect.InvocationTargetException
[ERROR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ERROR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]     at java.lang.reflect.Method.invoke(Method.java:606)
[ERROR]     at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR]     at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[ERROR] Caused by: scala.reflect.internal.Positions$ValidateException: Overlapping trees (63054,63049)
[ERROR]     at scala.reflect.internal.Positions$class.positionError$1(Positions.scala:105)
[ERROR]     at scala.reflect.internal.Positions$class.validate$1(Positions.scala:135)
[ERROR]     at scala.reflect.internal.Positions$class.validate$1(Positions.scala:145)
[ERROR]     at scala.reflect.internal.Positions$class.validate$1(Positions.scala:145)
[ERROR]     at scala.reflect.internal.Positions$class.validatePositions(Positions.scala:150)
[ERROR]     at scala.reflect.internal.SymbolTable.validatePositions(SymbolTable.scala:16)
[ERROR]     at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:103)
[ERROR]     at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:430)
[ERROR]     at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
[ERROR]     at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
[ERROR]     at scala.collection.Iterator$class.foreach(Iterator.scala:743)
[ERROR]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
[ERROR]     at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
[ERROR]     at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1625)
[ERROR]     at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1610)
[ERROR]     at scala.tools.nsc.Global$Run.compileSources(Global.scala:1605)
[ERROR]     at scala.tools.nsc.Global$Run.compile(Global.scala:1703)
[ERROR]     at scala.tools.nsc.Driver.doCompile(Driver.scala:34)
[ERROR]     at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[ERROR]     at scala.tools.nsc.Driver.process(Driver.scala:55)
[ERROR]     at scala.tools.nsc.Driver.main(Driver.scala:68)
[ERROR]     at scala.tools.nsc.Main.main(Main.scala)
[ERROR]     ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.6:compile (compile) on project scoverage-samples: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1
```

**Comment by BennyHill** [comment]
This looks stale, and most likely addressed with recent releases.

Could this now be closed?
